server:
  port: 9000
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:    name: auth-service
  config:    import: configserver:http://localhost:8888       
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true